### ISSUE TITLE
resource flagsmith_feature_state is not working

### ISSUE THREAD

**Issue by victorperin** [Flagsmith/terraform-provider-flagsmith#56]
Used tool versions:
```
go version go1.19.4 linux/amd64

Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/flagsmith/flagsmith v0.3.0
+ provider registry.terraform.io/hashicorp/aws v4.48.0
```

Logs:
```
flagsmith_feature_state.view_gamification_teams_ranking_state_dev: Creating...
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-flagsmith_v0.3.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7c86d5]

goroutine 63 [running]:
github.com/Flagsmith/terraform-provider-flagsmith/flagsmith.(*FeatureStateValue).ToClientFSV(...)
        github.com/Flagsmith/terraform-provider-flagsmith/flagsmith/models.go:17
github.com/Flagsmith/terraform-provider-flagsmith/flagsmith.(*FeatureStateResourceData).ToClientFS(0xc00035b220)
        github.com/Flagsmith/terraform-provider-flagsmith/flagsmith/models.go:83 +0x75
github.com/Flagsmith/terraform-provider-flagsmith/flagsmith.(*featureStateResource).Update(_, {_, _}, {{{{0xcb12f0, 0xc00011b9e0}, {0xabb9e0, 0xc00011af60}}, {0xc000283e90, 0x0, 0x0, ...}}, ...}, ...)
        github.com/Flagsmith/terraform-provider-flagsmith/flagsmith/resource_feature_state.go:251 +0x3db
github.com/Flagsmith/terraform-provider-flagsmith/flagsmith.(*featureStateResource).Create(_, {_, _}, {{{{0xcb12f0, 0xc00011b9e0}, {0xabb9e0, 0xc00011af60}}, {0xc000283e90, 0x0, 0x0, ...}}, ...}, ...)
        github.com/Flagsmith/terraform-provider-flagsmith/flagsmith/resource_feature_state.go:185 +0x7c5
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc0001b9600, {0xcae090, 0xc00011a900}, 0xc000515358, 0xc0005152f8)
        github.com/hashicorp/terraform-plugin-framework@v0.16.0/internal/fwserver/server_createresource.go:97 +0x8ce
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xcae090?, {0xcae090, 0xc00011a900}, 0xc00029c410, 0xc0005154c8)
        github.com/hashicorp/terraform-plugin-framework@v0.16.0/internal/fwserver/server_applyresourcechange.go:54 +0x4a8
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc0001b9600, {0xcae090?, 0xc00011a7b0?}, 0xc00029c190)
        github.com/hashicorp/terraform-plugin-framework@v0.16.0/internal/proto6server/server_applyresourcechange.go:52 +0x27b
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0001b50e0, {0xcae090?, 0xc00011a180?}, 0xc0001b60e0)
        github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov6/tf6server/server.go:816 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xb62a60?, 0xc0001b50e0}, {0xcae090, 0xc00011a180}, 0xc0001b6070, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003401e0, {0xcb1450, 0xc000183a00}, 0xc0004b0000, 0xc0003f5ce0, 0x10f10e0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0003401e0, {0xcb1450, 0xc000183a00}, 0xc0004b0000, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-flagsmith_v0.3.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

Terraform configuration:
```terraform

resource "flagsmith_feature" "view_gamification_teams_ranking" {
  feature_name = "view_gamification_teams_ranking"
  project_uuid = var.flagsmith_project_uuid
  description  = "Inside the dashboard page, there's a list of teams, enabling this flag will sort them by progress and show trophies for the first ones. Disabled will organize teams by name."
  type         = "STANDARD"
}

resource "flagsmith_feature_state" "view_gamification_teams_ranking_state_dev" {
  enabled          = true
  environment_key  = var.flagsmith_dev_key
  feature_id       = flagsmith_feature.view_gamification_teams_ranking.id
}
```

**Comment by gagantrivedi** [comment]
Hi @victorperin thanks for submitting this issue, it's feature_state_value attribute is required and not optional. I will have a fix out for that very soon, in the meantime you can update the schema to look like this

```
resource "flagsmith_feature_state" "view_gamification_teams_ranking_state_dev" {
  enabled          = true
  environment_key  = var.flagsmith_dev_key
  feature_id       = flagsmith_feature.view_gamification_teams_ranking.id
 feature_state_value = {
    type         = "unicode"
    string_value = "" # empty string if you don't want to set any value
  }
}

```

**Comment by victorperin** [comment]
Thanks, this makes sense. I've updated my terraform and worked perfectly.
