### ISSUE TITLE
Deleting a Terraform-managed feature in the console crashes the provider

### ISSUE THREAD

**Issue by strugee** [Flagsmith/terraform-provider-flagsmith#68]
STR:

1. Create a new feature in Terraform and run `terraform apply`
2. Log into the Flagsmith console
3. Click the red trash bin icon next to the new feature, type the feature name and click "Confirm Changes"
4. Run `terraform plan`

Expected result: Terraform plans to recreate the feature.

Actual result:

```
% terraform plan -out=tfplan
flagsmith_feature.new_standard_feature_foobar: Refreshing state...
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).ReadResource request was cancelled.
╵

Stack trace from the terraform-provider-flagsmith_v0.4.1 plugin:

panic: flagsmithapi: Error getting feature: {"detail":"Not found."}

goroutine 70 [running]:
github.com/Flagsmith/terraform-provider-flagsmith/flagsmith.(*featureResource).Read(0xc0005c0018, {0x18b9d68, 0xc000589050}, {{{{0x18bd150, 0xc00052ee70}, {0x16c6f00, 0xc00052e840}}, {0x18be670, 0xc000128500}}, 0xc0005c0040, ...}, ...)
	github.com/Flagsmith/terraform-provider-flagsmith/flagsmith/resource_feature.go:161 +0x335
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc0002274a0, {0x18b9d68, 0xc000589050}, 0xc000589140, 0xc0005fd608)
	github.com/hashicorp/terraform-plugin-framework@v1.0.1/internal/fwserver/server_readresource.go:97 +0x60e
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc0002274a0, {0x18b9d68?, 0xc000588f00?}, 0xc00058c480)
	github.com/hashicorp/terraform-plugin-framework@v1.0.1/internal/proto6server/server_readresource.go:52 +0x27b
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc000221180, {0x18b9d68?, 0xc000588270?}, 0xc00059a0c0)
	github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov6/tf6server/server.go:746 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x17716e0?, 0xc000221180}, {0x18b9d68, 0xc000588270}, 0xc0005ae000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a41e0, {0x18bd2b0, 0xc000295d40}, 0xc00051c000, 0xc000361e00, 0x1d0a490, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0002a41e0, {0x18bd2b0, 0xc000295d40}, 0xc00051c000, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-flagsmith_v0.4.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Note also that the plugin _also_ crashes if the feature flag is deleted entirely from the configuration - in this case the expected result would be a "your infrastructure matches the configuration" message from Terraform. Here's _that_ stack trace:

```
% terraform plan -out=tfplan
flagsmith_feature.new_standard_feature_foobar: Refreshing state...
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call.
│ The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-flagsmith_v0.4.1 plugin:

panic: flagsmithapi: Error getting feature: {"detail":"Not found."}

goroutine 27 [running]:
github.com/Flagsmith/terraform-provider-flagsmith/flagsmith.(*featureResource).Read(0xc0001a6950, {0x18b9d68, 0xc000583e60}, {{{{0x18bd150, 0xc000597a10}, {0x16c6f00, 0xc0005973e0}}, {0x18be670, 0xc00038e5a0}}, 0xc0001a6960, ...}, ...)
	github.com/Flagsmith/terraform-provider-flagsmith/flagsmith/resource_feature.go:161 +0x335
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc0001f9e40, {0x18b9d68, 0xc000583e60}, 0xc000583f50, 0xc0001d5608)
	github.com/hashicorp/terraform-plugin-framework@v1.0.1/internal/fwserver/server_readresource.go:97 +0x60e
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc0001f9e40, {0x18b9d68?, 0xc000583d10?}, 0xc0002c5680)
	github.com/hashicorp/terraform-plugin-framework@v1.0.1/internal/proto6server/server_readresource.go:52 +0x27b
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc00027a8c0, {0x18b9d68?, 0xc000583560?}, 0xc0001a9b00)
	github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov6/tf6server/server.go:746 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x17716e0?, 0xc00027a8c0}, {0x18b9d68, 0xc000583560}, 0xc000261ea0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002581e0, {0x18bd2b0, 0xc000102d00}, 0xc000585e60, 0xc000269f80, 0x1d0a490, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0002581e0, {0x18bd2b0, 0xc000102d00}, 0xc000585e60, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-flagsmith_v0.4.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Version info:

```% terraform -version
Terraform v1.3.8
on darwin_amd64
+ provider registry.terraform.io/flagsmith/flagsmith v0.4.1

Your version of Terraform is out of date! The latest version
is 1.4.4. You can update by downloading from https://www.terraform.io/downloads.html

% cat .terraform.lock.hcl
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/flagsmith/flagsmith" {
  version     = "0.4.1"
  constraints = "0.4.1"
  hashes = [
    "h1:1yUVPfiha0Ns+1y09DU5GnG78jsJ/V+5tTi7FV9jBis=",
    "zh:0cb945916d46cea5f3462d2a1640aad95c292daa12f1f233bf1589da1bb2b67a",
    "zh:0fcac6abb64cf0fbd17b64690403c5ba8f706bf01eba329297a1e2930752f1cb",
    "zh:1b62bdf0e4e022ada4169ce35265b959b84c4cfb369f5c750d72777befcf5d21",
    "zh:4d997fe1cb134b8ad0a32dc84af3c7e228401cf4baf06080c9cedb27797ecb43",
    "zh:4fd5be5293e2acd070a2ac4c431d9f26f11e79ae99ebe2c56899aadcb368a461",
    "zh:5990f6c166af491c56a710dab930193118d9419c584601f980f5f09382cf235e",
    "zh:890df766e9b839623b1f0437355032a3c006226a6c200cd911e15ee1a9014e9f",
    "zh:89332cb734d55db1e959d5edfe165423c147e4fce24f8970ce70946b5069403c",
    "zh:a599ae9bb9f5db90c9b85081254dadbe372b4bd63a2c4a0e2ce819dbba6102d9",
    "zh:a74fa1e90e8d99842662b151ad1f98948a540c991ae7e199fb3786aa69f864d3",
    "zh:bc127b646c122b5909989f851241e0ee649f2b43c834f1ff6110f52b0f8aac09",
    "zh:cded5bdaa5d9819bd622777903a40349123045fd05f41e8ce482b07cf78e36aa",
    "zh:f40d5ca134e14b3768a8e603dbf2730e215280ae8e64c75051c1f4cc9207cece",
    "zh:f6456a563ea86fa4fd41ffcfd0f4d810cf9eebf52a69776a2afcfb036db44ec1",
    "zh:fff4568616dbe7d5bf94d1a9dd30160d96fa7d10c912a1b64738991e64c6bf3d",
  ]
}
```

**Comment by matthewelwell** [comment]
Thanks @strugee, we will take a look into this and get back to you.

**Comment by strugee** [comment]
Thanks for the fix! Are y'all planning to cut a new version any time soon? This is a pretty game-breaking bug

**Comment by gagantrivedi** [comment]
Yep, we will put a release out on Monday
