### ISSUE TITLE
flagsmith feature state import crash 

### ISSUE THREAD

**Issue by yuhuyoyo** [Flagsmith/terraform-provider-flagsmith#84]
Stack trace from the terraform-provider-flagsmith_v0.5.1 plugin:

```
panic: flagsmithapi: Failed to get feature state

goroutine 49 [running]:
github.com/Flagsmith/terraform-provider-flagsmith/flagsmith.(*featureStateResource).Read(0xc00011ed48, ***0xd0cf20, 0xc00028c630***, ***0xd10f10, 0xc00029a8d0***, ***0xafba60, 0xc000297b60***, ***0xd12448, 0xc0000a0820***, 0x0, ...***, ...)
	github.com/Flagsmith/terraform-provider-flagsmith/flagsmith/resource_feature_state.go:230 +0x3ea
github.com/Flagsmith/terraform-provider-flagsmith/flagsmith.(*featureStateResource).Create(0xc00011ed48, ***0xd0cf20, 0xc00028c630***, ***0xd10f10, 0xc000296810***, ***0xafba60, 0xc00028daa0***, ***0xd12448, 0xc0000a0820***, ***0xd10f10, ...***, ...***, ...***, ...***, ...)
	github.com/Flagsmith/terraform-provider-flagsmith/flagsmith/resource_feature_state.go:173 +0x578
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc00016da20, ***0xd0cf20, 0xc00028c630***, 0xc00050f360, 0xc00050f300)
	github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/fwserver/server_createresource.go:97 +0x5b8
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xd0cf20?, ***0xd0cf20, 0xc00028c630***, 0xc000231040, 0xc00050f4d0)
	github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/fwserver/server_applyresourcechange.go:54 +0x4a8
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc00016da20, ***0xd0cf20?, 0xc00028c4e0?***, 0xc000230ff0)
	github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/proto6server/server_applyresourcechange.go:52 +0x27b
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0001e88c0, ***0xd0cf20?, 0xc000287b00?***, 0xc0000a81c0)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:816 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler(***0xbaa360?, 0xc0001e88c0***, ***0xd0cf20, 0xc000287b00***, 0xc0000a8150, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:419 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ec1e0, ***0xd111f8, 0xc000342820***, 0xc000263e60, 0xc0003403c0, 0x1173280, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc0001ec1e0, ***0xd111f8, 0xc000342820***, 0xc000263e60, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1[72](https://github.com/verily-src/terra-deployment/actions/runs/5019252588/jobs/8999565775#step:7:73)2 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.54.0/server.go:[96](https://github.com/verily-src/terra-deployment/actions/runs/5019252588/jobs/8999565775#step:7:97)4 +0x28a

Error: The terraform-provider-flagsmith_v0.5.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by gagantrivedi** [comment]
Hi @yuhuyoyo are you able to post the operation and config (removing anything sensitive) that caused this - that should help a lot

**Comment by yuhuyoyo** [comment]
it was a terraform error on our end (wrong env uuid)
